### ISSUE TITLE
Distribuir las propiedades

### ISSUE THREAD

**Issue by bsc0001** [ers0026/GESPRO_PracticaGestionCodigo#6]
Distribuir las propiedades cuando se genera runnable para no depender del fuente.

**Comment by ers0026** [comment]
Veo que te has dejado un archivo, sin actualizar la url  al fichero con las propiedades del proyecto, en concreto el SistInfGenWeb_4.0_src/src/main/ubu/digit/pesistence/SistInfData.java
Revisarlo y avísame cuando esté.

**Comment by bsc0001** [comment]
Cierto! Se me pasó guardar los cambios en ese archivo. Lo cambio ahora mismo y te aviso.
Menos mal que te has dado cuenta, gracias!

**Comment by ers0026** [comment]
Esta correctamente modificado.

**Comment by ers0026** [comment]
Bien perfecto, no se como se hará exactamente pero es una buena idea para salir del paso.
