### ISSUE TITLE
 Problemas con las últimas fechas.

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_PracticaGestionCodigo#7]
Me dispongo a cambiar los archivos:
    SistInfGenWeb_4.0_src/src/main/config.properties
    SistInfGenWeb_4.0_src/src/main/ubu/digit/htmlgen/DocHistoric.java
    SistInfGenWeb_4.0_src/src/main/ubu/digit/pesistence/SistInfData.java
    SistInfGenWeb_4.0_src/src/rsc-main/data/Historico.csv
    SistInfGenWeb_4.0_src/src/rsc-main/data/SistInf.ods

**Comment by bsc0001** [comment]
Por lo que estoy viendo, en general parece estar bien. Sin embargo, tengo dudas en el archivo SistInfGenWeb_4.0_src/src/main/ubu/digit/htmlgen/DocHistoric.java ¿estás seguro de que la condición del bucle de la línea 477 se hace así? ¿no debería incluir también la igualdad?

**Comment by ers0026** [comment]
Ahora lo compruebo.

**Comment by bsc0001** [comment]
Todo perfecto, ya casi está!
